Exclude net-sftp lib
askonev/onlyoffice-droplets-starter pull request #58
Opened 2022-10-14 16:55 UTC by askonev

Additionally, the use of ssh libraries below version 7.0.0 is strictly blocked because openssl 3.0 was previously used.

Maybe on Ubuntu below 22.04 where openssl 3.0 is not used everything will break. We'll have to check it out.

2022-10-14 17:27 UTC, ShockwaveNN requested changes

2022-10-14 17:27 UTC, ShockwaveNN commented on lib/data/static_data.rb
> +  TMP = "#{Dir.pwd}/tmp"
Maybe use system tmp directory? Via  `Dir.mktmpdir` or something like this?

2022-10-18 10:17 UTC, ShockwaveNN requested changes

2022-10-18 10:17 UTC, ShockwaveNN commented on lib/helpers/remote_configuration.rb
> +  def overwrite_dockerfile(tmpdir)
I think sending full path to `Dockerfile` in this method will be more precise, than sending dir and *hoping* that there is a Dockerfile inside

Same for `dot_env`

2022-10-18 19:01 UTC, ShockwaveNN approved these changes

2022-10-24 06:55 UTC, askonev commented
Apparently the DO has some sort of tricky ssh ban policy. If you reduce the wait after sftp request to less than 5 seconds, then the ban is on the fourth "fast" request. But I could not wait for the unbanning. So hardcode at sleep 5 is a normal solution. But sometimes it bans even for such time interval.

2022-10-24 09:43 UTC, ShockwaveNN requested changes

2022-10-24 09:43 UTC, ShockwaveNN commented on lib/ssh/ssh_wrapper.rb
> +    5.times do
Maybe extract similar code in `sftp_get` in `sftp_put` in new method and call it inside sftp_put something like
```
def sftp_put
  sftp_command("echo \"put #{host_path} #{remote_path}\" | sftp #{user}@#{ip}")
end
 ```

2022-10-24 13:36 UTC, ShockwaveNN approved these changes

2022-10-24 13:40 UTC, l8556 approved these changes

2022-10-24 13:40 UTC, merged